### ISSUE TITLE
Stel database omgeving in

### ISSUE THREAD

**Issue by TimonPost** [KBS-Groep-4/roei-je-rot#38]
We gebruiken entity framework [code first](https://entityframeworkcore.com/approach-code-first) met Microsoft sql server. 

- [x] Maak configuratie bestand, waar connectie string in staat (#48) .
- [x] Maak code om configuratie uit te lezen (#49) .
- [x] Maak database project `RoeiJeRot.Database` en `RoeiJeRot.Entities` #51
- [x] Installeer code first entity framework nuget packet. #68
- [x] Maak de classen representatie aan voor database tabellen in het project `RoeiJeRot.Entities`. #50. 
- [x] Maak entityframework core werken met project. #69
- [x] Maak migratie script die database structuur genereerd van classen tabel (#52)
- [x] Maak een docker image voor de database. #53
- [x] Maak migratie script die database structuur genereert van classen tabel. #52
