### ISSUE TITLE
Maak reservering voor boot.

### ISSUE THREAD

**Issue by TimonPost** [KBS-Groep-4/roei-je-rot#39]
Lid moet reservering kunnen maken voor boot. Voor een lid mag je een test lid gebruiken die niet besstaad. Dit kan als #42 gemaakt is geïmplementeerd worden. 

- [x] Maak schermontwerp reserveer boot scherm #58
- [x] Maak UI boot reserveer scherm. #56
- [ ] ~Maak restricties op boot huren:~
#29 
#28 
#23 
#24  (bedenk maximale tijd van te voren)
- [x] Implementeer boot reserveren met database data. #54
