### ISSUE TITLE
Maak lijst met gereserveerde boten, sorteerbaar op grootte, gebruik etc.

### ISSUE THREAD

**Issue by TimonPost** [KBS-Groep-4/roei-je-rot#40]
- [x] Maak gereserveerdebotenlijst schermontwerp. #62
- [x] Maak UI voor gereserveerdebotenlijst #61
- [x] Implementeer de gemaakte gereserveerdeboten lijst met database data. #59
- [x] Maak gereserveerde boten lijst sorteerbaar. #57
