### ISSUE TITLE
Login Gebruiker

### ISSUE THREAD

**Issue by TimonPost** [KBS-Groep-4/roei-je-rot#42]
Related: #15 

- [x] Maak login schermontwerp. #65
- [x] Maak UI voor login scherm. #66
- [x] Implementeer wachtwoord encrypt. #70
- [x] Implementeer login logica. #67
      - [ ] ophalen gebruiker uit database
      - [ ] checken van wachtwoord met gebruiker.
- [x] Test via userinterface de inlog module
